services:
  psta-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psta-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - BACKEND_HOST=${BACKEND_HOST:-}
      - BACKEND_PORT=${BACKEND_PORT:-3001}
    volumes:
      - /app/psta/nginx/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
